# Generated by Django 4.2.16 on 2024-11-24 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(2, '2 People'), (4, '4 People'), (6, '6 People')])),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('appointment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointment.appointment')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='table_booking.table')),
            ],
            bases=('appointment.appointment',),
        ),
    ]
