# Generated by Django 4.2.16 on 2024-11-26 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(default=datetime.time(10, 0))),
                ('closing_time', models.TimeField(default=datetime.time(22, 0))),
            ],
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='num_people',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='tablebooking',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AlterField(
            model_name='tablebooking',
            name='booking_time',
            field=models.DateTimeField(),
        ),
    ]
