# Generated by Django 4.2.16 on 2024-11-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_booking', '0002_restaurantsettings_tablebooking_num_people_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='num_people',
            field=models.IntegerField(default=1),
        ),
    ]
