# Generated by Django 4.2.16 on 2024-12-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('number_of_guests', models.PositiveIntegerField()),
                ('contact_number', models.CharField(max_length=15)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
            ],
        ),
    ]
