# Generated by Django 4.2.16 on 2024-12-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_reservation_customer_name_reservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
